apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertmanager
  - servicemonitors
  - prometheus-rules
  - scrapeconfigs
  - grafana/datasources
  - grafana/dashboard-configmaps
