grafana:
  enabled: true

  adminPassword: admin123

  persistence:
    enabled: false
    storageClassName: longhorn
    size: 10Gi

  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL

    datasources:
      enabled: true

alertmanager:
  enabled: true

  alertmanagerSpec:
    replicas: 1

prometheusOperator:
  image:
    registry: quay.io
    repository: prometheus-operator/prometheus-operator
    tag: v0.92.1

prometheus:
  enabled: true

  prometheusSpec:

    retention: 2d

    replicas: 1

    ##################################################
    # Cross Namespace Discovery (Phase 10)
    ##################################################

    serviceMonitorSelector: {}

    serviceMonitorNamespaceSelector: {}

    podMonitorSelector: {}

    podMonitorNamespaceSelector: {}

    ruleSelector: {}

    ruleNamespaceSelector: {}

    ##################################################
    # ScrapeConfig Discovery (Phase 11)
    ##################################################

    scrapeConfigSelector: {}

    scrapeConfigNamespaceSelector: {}

    ##################################################
    # External Labels
    ##################################################

    externalLabels:
      cluster: prod

    ##################################################
    # Storage
    ##################################################

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path

          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 10Gi
