apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: recording-rules

spec:
  groups:

  - name: cluster

    rules:

    - record: cluster:cpu_usage:rate5m

      expr: |
        sum(
          rate(container_cpu_usage_seconds_total[5m])
        )
