apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-prometheus
  namespace: monitoring

  labels:
    grafana_datasource: "1"

data:
  prometheus.yaml: |
    apiVersion: 1

    datasources:
    - name: Prometheus
      uid: prometheus
      type: prometheus
      access: proxy
      isDefault: true
      url: http://prometheus-operated.monitoring.svc:9090
